apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret
  namespace: cephfs
data:
  key: QVFEdFR1ZGRxU2RHTnhBQVhhTURuZGRkV0l0TE81K0hTUDZob3c9PQ==

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-dynamic
  namespace: cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: 10.136.11.25:6789,10.136.11.26:6789,10.136.11.27:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: cephfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-test
  namespace: cephfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-dynamic
  resources:
    requests:
      storage: 1Gi