apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  "8500": consul/consul:8500
  "5432": postgresql/postgresql10:5432
  "5431": postgresql/postgresql10-read:5432
  "6379": redis/redis-master:6379
  "6378": redis/redis-slave:6379
  "1022": gitlab/gitlab:22
  "3306": mysql/mysql:3306
  "27017": mongo/mongodb:27017
  "5672": rabbit/rabbitmq-rabbitmq-ha:5672
  "15672": rabbit/rabbitmq-rabbitmq-ha:15672